# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDB', '0002_auto_20170213_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdbuser',
            name='phone_number',
            field=models.BigIntegerField(default='12223334444'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 21, 0, 6, 26, 695874)),
        ),
    ]
