# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 01:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDB', '0003_auto_20170214_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_email',
            field=models.EmailField(default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_office',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_set', to='MDB.Course'),
        ),
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 21, 1, 3, 15, 451554)),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mdbuser',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
