# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDB', '0005_auto_20170227_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 7, 1, 37, 46, 2880)),
        ),
        migrations.AlterField(
            model_name='mdbuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
